version: 2

build:
  tools:
    python: "3.8"

sphinx:
    configuration: doc/source/conf.py

python:
    install:
        - requirements: doc/requirements.txt
        - requirements: requirements.txt
